### PR TITLE
large update

### PR DESCRIPTION
**Pull request by yalov**
* Add Localization
* Add parameters of the WarpDrive in the config of the module
    * upgradeStatus
    * drivePower
    * containmentFieldPower
* Add scaled 5.0m part
* Add four B9PS PartUpgrades instead of the one hardcoded: 
    * upgradeStatus (Pigeon, Mallard, Osprey, Peregrine)
    * drivePower (x1, x2, x4, x8)
    * containmentFieldPower (x1, x2, x3, x4)
* Supports of the CTT
* Fixed fov bug, that had appeared on deactivating warpdrive in the map view
* Replace the toolbar button with a KSPEvent button in the PAW, 
   because the Warpotron GUI only relates to the AlcubierreDrive module, and nothing else.
   several other WarpDrive Mods also have GUI opened using PAW.
  

* Warpotron 9000
    * Add Tooltips on the Warpotron GUI
    * Add Speed Factor scale line on the Warpotron GUI
    * put more helpful values on minimized Warpotron GUI
    
    

Corresponding CKAN dependency changes, that need to be made:
* Not depends on ToolbarController 
* Recommends B9PartSwitch
* Supports CommunityTechTree

Also I have found one bug:
* stock theme (enabled in the settings) looks like unity theme

### CODE REVIEW

**Comment by yalov** [comment]
Todo segment is for you 😀

**Comment by linuxgurugamer** [comment]
Do you have a simple warp vessel I can include as a sample vessel?

**Comment by linuxgurugamer** [comment]
Also, an FYI, due to the use of ClickThroughblocker, it also needs the ToolbarController, they now depend on each other

**Comment by linuxgurugamer** [comment]
I've also fixed the skin bug you mentioned

**Pull request merged**
